// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ_iGRmeEyDyek9N7LyUeBGAYTM0rhWlU',
    appId: '1:1013391594194:web:bc9c31a8c194dc0639d30b',
    messagingSenderId: '1013391594194',
    projectId: 'habit-tracker-app-737ae',
    authDomain: 'habit-tracker-app-737ae.firebaseapp.com',
    storageBucket: 'habit-tracker-app-737ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_A7LDLY9-bpcvJ_RX3FwQWO-K5HtC6yg',
    appId: '1:1013391594194:android:355b5a94bd246a2539d30b',
    messagingSenderId: '1013391594194',
    projectId: 'habit-tracker-app-737ae',
    storageBucket: 'habit-tracker-app-737ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACNDw5ohpQDc3OC13shpcPOdsTYguqd9E',
    appId: '1:1013391594194:ios:977dbc2c161e70c639d30b',
    messagingSenderId: '1013391594194',
    projectId: 'habit-tracker-app-737ae',
    storageBucket: 'habit-tracker-app-737ae.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACNDw5ohpQDc3OC13shpcPOdsTYguqd9E',
    appId: '1:1013391594194:ios:977dbc2c161e70c639d30b',
    messagingSenderId: '1013391594194',
    projectId: 'habit-tracker-app-737ae',
    storageBucket: 'habit-tracker-app-737ae.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ_iGRmeEyDyek9N7LyUeBGAYTM0rhWlU',
    appId: '1:1013391594194:web:29f5f6ad5520bf2b39d30b',
    messagingSenderId: '1013391594194',
    projectId: 'habit-tracker-app-737ae',
    authDomain: 'habit-tracker-app-737ae.firebaseapp.com',
    storageBucket: 'habit-tracker-app-737ae.firebasestorage.app',
  );
}
